# Generated by Django 3.1.2 on 2020-10-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201013_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='District',
        ),
    ]
