# Generated by Django 3.1.2 on 2020-10-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='newsletter_choice',
            field=models.CharField(choices=[('email', 'email'), ('phone', 'phone'), ('telegram', 'telegram')], default='email', max_length=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
