# Generated by Django 3.1.2 on 2020-10-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201016_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='okrug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
